AssetDir = "."
BaseDir = ""
Branding = "Metabuzz"
Ganalytics = ""
Language = "en"
Mode = ""
DefaultTheme = ""

[Author]
  FullName = "Tom Campbell"
  URL = "https://metabuzz.com"
  Role = ""

[Company]
  Name = "Metabuzz"
  URL = "https://metabuzz.com"
  HeaderLogo = ""

[MarkdownOptions]
  HighlightStyle = "github"

[Social]
  DeviantArt = ""
  Facebook = "https://www.facebook.com/getmetabuzz"
  Github = "https://github.com/metabuzz"
  Gitlab = ""
  Instagram = ""
  LinkedIn = ""
  Pinterest = "https://www.pinterest.com/metabuzz/"
  Reddit = ""
  Tumblr = ""
  Twitter = "https://twitter.com/trymetabuzz"
  Weibo = ""
  YouTube = ""

[WebPages]
