AssetDir = "."
BaseDir = ""
Branding = "Metabuzz"
Ganalytics = ""
Language = "en"
Mode = ""
Theme = ""

[Author]
  FullName = ""
  URL = ""
  Role = ""

[Company]
  Name = ""
  URL = ""
  HeaderLogo = ""

[MarkdownOptions]
  HighlightStyle = "github"

[Social]
  DeviantArt = ""
  Facebook = ""
  Github = ""
  Gitlab = ""
  Instagram = ""
  LinkedIn = ""
  Pinterest = ""
  Reddit = ""
  Tumblr = ""
  Twitter = ""
  Weibo = ""
  YouTube = ""

[WebPages]
