Name = ""
Branding = "Yo brand this"
CommonSubDir = ".common"
Language = "en"
Mode = ""
Theme = ""
AssetDir = "."
BaseDir = ""
Publish = "/Users/tom/code/m2/fobar/.pub"
Headers = "/Users/tom/code/m2/fobar/.headers"
Ganalytics = ""

[MarkdownOptions]
  HighlightStyle = "github"

[Company]
  Name = ""
  URL = ""
  HeaderLogo = ""

[Social]
  DeviantArt = ""
  Facebook = ""
  Github = ""
  Gitlab = ""
  Instagram = ""
  LinkedIn = ""
  Pinterest = ""
  Reddit = ""
  Tumblr = ""
  Twitter = ""
  Weibo = ""
  YouTube = ""
