Branding = ""
Description = ""
Stylesheets = ["sizes.css", "page-wide.css", "theme-light.css", "new-wide.css", "responsive.css"]
RootStylesheets = ["reset.css", "fonts.css", "layout.css"]
PathName = ""

[Nav]
  HTML = ""
  #File = "nav.md"

[Header]
  HTML = "<header>PURE HTML HEADER, YO</header>"
  File = "header.md"

[Article]
  HTML = ""
  File = "article.md"

[Footer]
  HTML = "<footer>YASS PURE HTML FOOTER!</footer>"
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
