Branding = "Default Theme"
Description = ""
Stylesheets = ["theme-light.css", "1.css"]
RootStylesheets = ["reset.css", "fonts.css", "tufte.min.css"]
PathName = ""

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = ""

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
