Name = "from"
Branding = ""
CommonSubDir = ".common"
Language = "en"
Mode = ""
Theme = ""
AssetDir = "."
BaseDir = ""
Publish = ".pub"
Headers = ".headers"
Ganalytics = ""

[MarkdownOptions]
  HighlightStyle = "github"

[Company]
  Name = ""
  URL = ""
  HeaderLogo = ""

[Social]
  DeviantArt = ""
  Facebook = ""
  Github = ""
  Gitlab = ""
  Instagram = ""
  LinkedIn = ""
  Pinterest = ""
  Reddit = ""
  Tumblr = ""
  Twitter = ""
  Weibo = ""
  YouTube = ""
