#!/bin/sh
# Creates a new theme demo directory.
# Copies the wide directory to the dir named on the command line,
# then searches and replaces the theme name in .md files as required.
# You still have a number of things to personalize, documented below.
[ ! $1 ] && echo "Please specify the new theme name" && exit 1

# Replace with your favorite command line editor, which is
# of course nvim
editor=nvim
mkdir -p $1
echo "Copying the wide theme to ${1}" 
cp wide/*.md $1
cp wide/*.sidebar $1
[ ! -d $1 ] && echo "theme directory ${1} doesn't exist" && exit 1
declare -a filenames=(
	'dark.md'
	'light.md'
	'light-sidebar-left.md'
	'light-sidebar-right.md'
	'dark-sidebar-left.md'
	'dark-sidebar-right.md'
  'right-sidebar-example.md'
  'left-sidebar-example.md'
  'dark-sidebar-left.sidebar'
  'dark-sidebar-right.sidebar'
  'light-sidebar-left.sidebar'
  'light-sidebar-right.sidebar'
	)

dest=$1

# Displays prompt, and waits for user to answer 
# with either a Y or N. Repeats prompt until
# it gets one of those two.
# Return 0 if answer was Y,
# return 1 if answer was N.
# 
# Answer is in the global variable $?
#
# Example usage:
#   wait_for_yes "Please enter y or n "
wait_for_yes() {
  while :; do
    #echo -n "${1} "
    echo "${1} "
    read answer
    case "$answer" in
      [Yy])
        return 0
        ;;
      [Nn])
        return 1
        ;;
      *)
        ;;
    esac
  done
}



for file in "${filenames[@]}"
do
	# Display the commmand to execute...
	echo "${file}"
	# And execute the command
  # Thank you, Sundeep!
  # https://stackoverflow.com/questions/62254934/zsh-on-macos-1-not-expanding-in-a-sed-script?noredirect=1#comment110102949_62254934
  sed -i.bak -E 's/theme=\"(.*).*\"/\theme=\"'$1'\"/' $dest/$file > $dest/$file.bak
  #sed -E 's/theme=\"(.*).*\"/\theme=\"'$1'\"/' < $dest/$file 
done
  sed -i.bak -E 's/DemoTheme=\"(.*).*\"/\DemoTheme=\"'$1'\"/' $1/index.md > $1/index.bak
echo "Don't forget to fix Next in the front matter. That links to the next theme."
echo "Now customize the following:"
echo "* Replace ${dest}/intro.md with any images, text or other material you"
echo "* would like to precede the kitchensink with"
echo "* Replace ${dest}/description.md with a pitch describing the theme"
echo "* Replace ${dest}/left-sidebar-example.md with left sidebar content for this theme"
echo "* Replace ${dest}/right-sidebar-example.md with right sidebar content for this theme"
echo "* Create a 1280x1280 PNG image of the best-looking version of the theme and save it as theme-1280x1024.png"
echo "* Create a 1280x1280 PNG image of the best-looking version of the theme and save it as theme-1280x1280.png"
echo "* Create 6 thumbnails (ideally 3 light, 3 dark) of themes and name them as needed:"
echo "  light-sidebar-left-256x256.png"
echo " light-sidebar-right-256x256.png)                               
* ![Thumbnail screenshot of ](light-sidebar-none-256x256.png)                                
* ![Thumbnail screenshot of ](dark-sidebar-left-256x256.png)                                 
* ![Thumbnail screenshot of ](dark-sidebar-right-256x256.png)                                
* ![Thumbnail screenshot of ](dark-sidebar-none-256x256.png)                                 
      
4

wait_for_yes "Run nvim on these files?"
if [ $? == 0 ]; then
$editor ${dest}/index.md ${dest}/intro.md ${dest}/description.md ${dest}/left-sidebar-example.md ${dest}/right-sidebar-example.md 
fi


wait_for_yes "Delete the .bak files?"
if [ $? == 0 ]; then
rm $1/*.bak 
fi

exit 0



