#!/bin/zsh
declare -a files=(
  'reset.css'
  'layout.css'
  'responsive.css'
  'page-pillar.css'
  'page-wide.css'
  'sidebar-left.css'
  'sidebar-right.css'
  'sizes.css'
  'new-wide.css'
	)


if [ $# -ne 2 ]; then
  #echo 1>&2 "$0: not enough arguments"
  echo "Need the name of 2 themes to compare"
  exit 2
fi
echo "Comparing theme ${1} to theme ${2}"


# Loop through the array
for file in "${files[@]}"
do
	# And execute the command
	diff ../.mb/themes/$1/$file ../.mb/themes/$2/$file | less
	#diff ../.mb/themes/$1/$file ../.mb/themes/$2/$file 
	echo "Comparing ../.mb/themes/${1}/${file} ../.mb/themes/${1}/${file} "
done

:'
reset.css
layout.css
responsive.css
page-pillar.css
page-wide.css
sidebar-left.css
sidebar-right.css
sizes.css
new-wide.css
theme-dark.css
theme-light.css

new-wide.toml

article.md
footer.md
header.md
nav.md
sidebar.md
'


