Branding = "Try these featured Metabuzz themes live"
Language = "en"
Theme = "reference"
Dir = "/Users/tom/code/d2/gal"
AssetDir = "assets"
BaseDir = ""
Publish = ".pub"
ThemeDir = "/Users/tom/code/mb/.mb/themes"
Ganalytics = "UA-152078779-1"
ExcludeDirs = [ ".sample", ".common"]

[markdownoptions]
#highlightstyle="github"
highlightstyle="autumn"

[[Authors]]
fullname = "Tom Campbell"
url = "tom.im"
role = "Chief developer"

[company]
name = "METABUZZ"
HeaderLogo = "metabuzz-red.svg"
URL = "https://metabuzz.com"

[social]
github = "https://github.com/tomcam/d2"
linkedin = "https://www.linkedin.com/in/tomcam/"
twitter = "https://twitter.com/tomcam"
reddit = "https://reddit.com/u/tomcam"
youtube = "https://youtube.com/tomcam3"
instagram = "https://www.instagram.com/mktbup/"

[List]
#lightlogo="globe-24x24-darkpurple.svg"
# cp ~/Downloads/card-bulleted-outline-40x40.svg 
lightlogo = { light="metabuzz-light.svg", dark="metabuzz-dark.svg" }
# card-bulleted-outline-40x40.svg 
#logomode = { light="metabuzz-light.svg", dark="metabuzz-dark.svg" }
#logomode = { light="card-bulleted-outline-40x40.svg", dark="metabuzz-dark.svg" }
logomode = { light="metabuzz-red.svg", dark="card-bulleted-outline-40x40.svg" }
#theme = { light="lightlogo.svg", dark="darklogo.svg" }
